# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af2e6174cd946a3ab557bc26e52ef927d43efb67ce2d5ea7d1e0f07e5e10add89de9a6905d9642cdc7e621b559a88087fd325fb826a30ad8d3a1f5c0c184d4bf

test:
  secret_key_base: 943f552834b630845b3aa42bc6ab4e2d3f90cce6c6739a3181ff870a0823dc5c1756cd03339c0569456e7dd4c8ff59b4115f5b556b9484e16dc541ecf8201c16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
